// UEFA Fantasy 联赛成员与网站抽签昵称的固定映射。
// drawName 是网站唯一展示名，也是分数、阵容和队长数据导入时的内部匹配键。
window.PENGUIN_LEAGUE_ROSTERS = {
  regions: {
    arctic: [
      { fantasyTeam: "Eva", displayName: "CHI", drawName: "Eva" },
      { fantasyTeam: "九命黑獭一统天下", displayName: "Alex", drawName: "九命黑獭一统天下" },
      { fantasyTeam: "Kw拜诶噻", displayName: "Kw", drawName: "Kw" },
      { fantasyTeam: "Shuo", displayName: "Shuo", drawName: "Shuo" },
      { fantasyTeam: "珠海兵工厂", displayName: "Ericking Arsenal", drawName: "殷少Eric" },
      { fantasyTeam: "Fitz", displayName: "fitz", drawName: "fitz" },
      { fantasyTeam: "当代丁蟹", displayName: "Zach", drawName: "当代丁蟹" },
      { fantasyTeam: "欧冠你们的王回来了", displayName: "Warmer", drawName: "warmer" },
      { fantasyTeam: "美式加冰", displayName: "Kimi", drawName: "Kimi" },
      { fantasyTeam: "最美95花周也大美女全球后援会", displayName: "萨默维尔", drawName: "第一边锋萨默维尔" },
      { fantasyTeam: "jingluo", displayName: "Ray", drawName: "镜落" },
      { fantasyTeam: "heavy serenade", displayName: "micky", drawName: "Micky VDV" },
      { fantasyTeam: "UEFAntasis", displayName: "摩二哥", drawName: "UEFAntasis" },
      { fantasyTeam: "penguin", displayName: "企鹅", drawName: "企鹅" },
      { fantasyTeam: "座山雕", displayName: "座山雕", drawName: "座山雕" },
      { fantasyTeam: "JZhuoyan", displayName: "DU", drawName: "拙言" },
      { fantasyTeam: "johnnyocean", displayName: "Jim Ocean", drawName: "欧巡" },
      { fantasyTeam: "AVG", displayName: "AVERAGE", drawName: "AVG" },
      { fantasyTeam: "XHS公众号请关注无敌紫葱酱！", displayName: "Chichung So", drawName: "紫葱酱" },
      { fantasyTeam: "nbw", displayName: "Chyancheng Wu", drawName: "nbw" },
      { fantasyTeam: "Yamine Lmao", displayName: "Kevin", drawName: "Yamine Lmao" },
      { fantasyTeam: "DDDD", displayName: "Wei", drawName: "DDDD" },
      { fantasyTeam: "放棄是極其難", displayName: "安德", drawName: "喝呀" },
      { fantasyTeam: "W^2", displayName: "W²", drawName: "W" },
      { fantasyTeam: "Pluto D", displayName: "Du", drawName: "Pluto" },
      { fantasyTeam: "ZhallWin", displayName: "Kiki", drawName: "狗蛋kk" },
      { fantasyTeam: "Jzl", displayName: "vx", drawName: "江逐流" },
      { fantasyTeam: "Dream Tickets", displayName: "Steven", drawName: "Steven" },
      { fantasyTeam: "蒂亚鸽鸽鸽", displayName: "南无十三鸽", drawName: "Diego W" },
      { fantasyTeam: "Verydisco", displayName: "Dapeng", drawName: "verydisco" },
      { fantasyTeam: "X Team", displayName: "Lik Kee", drawName: "x team" },
      { fantasyTeam: "dongma", displayName: "kingwenwei", drawName: "东马" },
      { fantasyTeam: "KisScam", displayName: "Bad K", drawName: "Bad K" },
      { fantasyTeam: "Baros15", displayName: "JYC15", drawName: "baros15" },
      { fantasyTeam: "Chelsea Mata", displayName: "stone", drawName: "切尔西萌塔" },
      { fantasyTeam: "Kusuri", displayName: "Romeo Zhao", drawName: "kusuri" },
    ],
    antarctic: [
      { fantasyTeam: "Noodle FC", displayName: "面条", drawName: "面条" },
      { fantasyTeam: "wc1018", displayName: "鬼嗨hi", drawName: "鬼嗨" },
      { fantasyTeam: "Lens", displayName: "寂", drawName: "Lambert luo" },
      { fantasyTeam: "美凌格欧冠分格", displayName: "foreveraul7", drawName: "BA" },
      { fantasyTeam: "联曼", displayName: "Jia", drawName: "联曼" },
      { fantasyTeam: "红衫圣殿", displayName: "Eric", drawName: "Eric" },
      { fantasyTeam: "Yummy", displayName: "Ethan", drawName: "yummy" },
      { fantasyTeam: "Livy Lv", displayName: "Yan", drawName: "Y" },
      { fantasyTeam: "saru", displayName: "nianzu", drawName: "saru" },
      { fantasyTeam: "remember", displayName: "remember", drawName: "remember" },
      { fantasyTeam: "yu99", displayName: "hu", drawName: "yu128" },
      { fantasyTeam: "Frank Hua", displayName: "Hua", drawName: "Frank Hua" },
      { fantasyTeam: "fantasynba.cn欢迎各位大佬", displayName: "Golden_Sheva🇨🇳", drawName: "公瑾" },
      { fantasyTeam: "Xi9Li", displayName: "Danny", drawName: "Dannyyyyy" },
      { fantasyTeam: "Team Blue", displayName: "Enzo", drawName: "enzowang" },
      { fantasyTeam: "TakahashiAkira", displayName: "takahashi", drawName: "高桥明" },
      { fantasyTeam: "FAIAAA", displayName: "FAIAAA", drawName: "LQ女神" },
      { fantasyTeam: "Acidboy", displayName: "acidboy", drawName: "Acidboy" },
      { fantasyTeam: "列侬贝尔两翼齐飞 我至尽还记得 ", displayName: "Conan Joe", drawName: "conan joe" },
      { fantasyTeam: "蒂尔尼又没欧冠踢了", displayName: "Levine", drawName: "蒂兰基尔尼" },
      { fantasyTeam: "MutdBJ", displayName: "垫底超人00", drawName: "垫底超人00" },
      { fantasyTeam: "光之围棋俱乐部", displayName: "进藤光", drawName: "进藤光" },
      { fantasyTeam: "战Siu小师", displayName: "Nirvana", drawName: "Nirvana" },
      { fantasyTeam: "ZHIYU FC", displayName: "ZHIYU", drawName: "ZHIYU" },
      { fantasyTeam: "Nedved", displayName: "Nedved", drawName: "纳尼" },
      { fantasyTeam: "Elliott", displayName: "junxi", drawName: "Elliott" },
      { fantasyTeam: "Southcote Bargain", displayName: "Sadio", drawName: "Snepia Fepson" },
      { fantasyTeam: "DNMCCB", displayName: "wengowen1985", drawName: "珍惜眼前人❤️" },
      { fantasyTeam: "lulucool", displayName: "Chen", drawName: "lulucool" },
      { fantasyTeam: "Vamos Espana", displayName: "Russ", drawName: "小火龙" },
      { fantasyTeam: "BeatEnzoWang", displayName: "Enzo", drawName: "丢屁" },
      { fantasyTeam: "爱你我不能说", displayName: "Hall", drawName: "英国人画像" },
      { fantasyTeam: "halfbrain", displayName: "hb", drawName: "halfbrain" },
      { fantasyTeam: "换汤不换药", displayName: "Jiang", drawName: "Jiang" },
      { fantasyTeam: "Bill goes to EUROPA", displayName: "Bill", drawName: "比尔" },
      { fantasyTeam: "EURO BEN", displayName: "欧洲笨", drawName: "Euro Ben" },
    ],
  },
  extras: {
    arctic: [{ fantasyTeam: "蒂尔尼又没欧冠踢了", displayName: "Levine" }],
    antarctic: [{ fantasyTeam: "penguin", displayName: "企鹅" }],
  },
};
